# Generated by Django 6.0.6 on 2026-07-25 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='cartitemaddon',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.addon'),
        ),
        migrations.AddField(
            model_name='cartitemaddon',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_addons',
            field=models.ManyToManyField(blank=True, related_name='cart_items', through='cart.CartItemAddon', to='menu.addon'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitemaddon',
            unique_together={('cart_item', 'addon')},
        ),
    ]
