# Generated by Django 6.0.6 on 2026-07-20 11:30

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=user.models.get_default_preferences, null=True),
        ),
    ]
